### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by GanggangDong** [xyj77/MCF-3D-CNN#3]
Hi, Dr. Xiao how to get a copy of the dataset?

**Comment by xyj77** [comment]
Sorry to reply so late. I've graduated for a year, please contact the correspondent author at Dawei-yang@vip.163.com.

**Comment by xyj77** [comment]
> Hi, Dr. Xiao how to get a copy of the dataset?

Sorry to reply so late. I've graduated for a year, please contact the correspondent author at Dawei-yang@vip.163.com.

**Comment by xyj77** [comment]
Sorry to reply so late. I've graduated for a year, please contact the correspondent author at Dawei-yang@vip.163.com.
